version: 2
jobs:
  build:
    working_directory: ~/d-landing-p
    docker:
    - image: circleci/node:8.11.3
    steps:
    - checkout
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Install dependencies
        command: 'sudo yarn install'
    - save_cache:
        name: Save Yarn Package Cach
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn
    - run:
        name: Run Typescript
        command: 'yarn build-ts'
    - run:
        name: Run Typescript lint
        command: 'yarn tslint'
    - run:
        name: Run tests
        command: 'yarn test'
